name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version tag
        id: version
        run: |
          VERSION=$(git describe --tags --abbrev=0 || echo "latest")
          echo "Version: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }} .
      - name: Push Docker image to GitHub Packages
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}
